## How does data exist in a neural network?

#### Scaler (0 Dimension)

In [1]:
import numpy as np
A = np.array(15)
print(A)



15


In [4]:
A.ndim


0

#### Vector (1 Dimension)

In [3]:
B = np.array([1,2,3])
print(B)

[1 2 3]


In [5]:
B.ndim
# 1 dimensional array 

1

#### Matrix (2 Dimensions)

In [6]:

C = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
print(C)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]


In [7]:
C.ndim

2

In [8]:
import tensorflow as tf

D = tf.constant([[1,3,5],
                 [2,4,6]])
print(D)
# 2 dimensional constant tensor, we can't change the value of the tensor

tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [12]:
D.ndim

2

In [13]:
E = tf.Variable([[3, 2],
                 [5, 2],
                 [5, 2]])
print(E)
# 2 dimensional variable tensor, we can change the value of the tensor

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 2],
       [5, 2],
       [5, 2]], dtype=int32)>


In [16]:
E.shape
# Shape[3,2] means 3 rows and 2 columns

TensorShape([3, 2])

In [17]:
F = tf.constant([[1.0, 2.0, 3.0], 
                 [4.0, 5.0, 6.0]])
print(F.get_shape())
print(F.shape.dims)
# get_shape() and shape.dims are used to get the shape of the tensor
# [Dimension(2), Dimension(3)] means 2 rows and 3 columns

(2, 3)
[Dimension(2), Dimension(3)]


#### Tensor Object to Numpy Array

In [18]:
m = tf.constant([[1, 2], [3, 4]]) # 2x2 matrix                
n = tf.add(m, 1) # Add 1 to each element

m.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [19]:
n.numpy()

array([[2, 3],
       [4, 5]], dtype=int32)

In [20]:
tf.multiply(m, n).numpy()

array([[ 2,  6],
       [12, 20]], dtype=int32)

#### Three or more Dimensions

In [21]:
G = np.array([[[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]],
              
              [[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]],
              
              [[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]]])
print(G)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]


In [22]:
G.ndim

3

#### Shape

In [23]:
# Shape changes
tenso = tf.constant([[3, 2],
                    [5, 2],
                    [9, 5],
                    [1, 3]])

# shape = [rows, columns]
shape_tenso = tf.reshape(tensor = tenso,
                             shape = [1, 8])

print(('Before reshapping:\n{0}').format(
    tenso.numpy()
))
print(('\nAfter reshapping:\n{0}').format(
    shape_tenso.numpy()
))

Before reshapping:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

After reshapping:
[[3 2 5 2 9 5 1 3]]


#### Tensor Matrix Multiplication

In [26]:
H = tf.constant([[1, 2], 
                 [4, 5]])

I = tf.constant([[5],
                [2]])

J = tf.matmul(H, I)

print(J)

tf.Tensor(
[[ 9]
 [30]], shape=(2, 1), dtype=int32)


#### MNIST Dataset Shape, Dimension

In [27]:
import tensorflow as tf
from tensorflow import keras

# Load the data
data = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = data.load_data()


29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 3us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 25s 1us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 4s 1us/step


In [28]:
print(train_images.ndim)
# 3 dimensions, 1st dimension is the number of images, 2nd and 3rd dimensions are the size of the image

3


In [29]:
print(train_images.shape)
# 60000 images of size 28x28 (row X column), 1st dimension is the number of images, 2nd and 3rd dimensions are the size of the image

(60000, 28, 28)


In [30]:
print(test_images.shape)

(10000, 28, 28)


In [31]:
test_image1 = test_images[10:100]
print(test_image1.shape)
# 10:100 means from 10th index to 99th index

(90, 28, 28)


#### Data Batch

In [32]:
# Data Batch helps to load the data in batches
batch = train_images[:128]
batch
# that means 128 images are loaded in the batch

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 